name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.2.0
    - name: Install Node v12
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: npm install, build, and test
      run: |
        npm install
        npm run lint:ci
        npm run test:ci
        npm run build
        npm run docs:build
      env:
        CI: true
    - name: coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    # publish to latest if on master branch
    - name: release master
      if: ${{ github.ref == 'master' }}
      run:
        npx semantic-release
        npm run docs:deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    # publish pre-release if on PR branch
    - name: release non-master version
      if: ${{ github.ref != 'master' }}
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
